name: Release Agent ALL

on:
  workflow_dispatch:

jobs:
  build-mac-release:
    runs-on: macos-11
    permissions:
      contents: write
      pull-requests: read
    strategy:
      matrix:
        arch:
          - x86_64-apple-darwin
          - aarch64-apple-darwin
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.arch }}
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target ${{ matrix.arch }} --package east_agent

      - uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.arch }}
          path: target/${{ matrix.arch }}/release/east*
        
      - run: zip -j agent_${{ matrix.arch }} target/${{ matrix.arch }}/release/east*
    
      - name: Release Drafter
        id: create_release
        uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}        

      - name: Upload Release Asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} 
          asset_path: agent_${{ matrix.arch }}.zip
          asset_name: agent_${{ matrix.arch }}.zip
          asset_content_type: application/zip

  build-windows-release:
    runs-on: windows-latest
    permissions:
      contents: write
      pull-requests: read
    strategy:
      matrix:
        arch:
          - x86_64-pc-windows-msvc        
          - i686-pc-windows-msvc

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.arch }}
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target ${{ matrix.arch }} --package east_agent

      - uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.arch }}
          path: target/${{ matrix.arch }}/release/east*

      - run: copy target/${{ matrix.arch }}/release/east* ./

      - uses: thedoctor0/zip-release@0.7.1
        with:
          type: zip
          filename: agent_${{ matrix.arch }}.zip
          directory: target/${{ matrix.arch }}/release
          path: ./east*.exe
    
      - name: Release Drafter
        id: create_release
        uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}   

      - name: Upload Release Asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} 
          asset_path: agent_${{ matrix.arch }}.zip
          asset_name: agent_${{ matrix.arch }}.zip
          asset_content_type: application/zip

  build-linux-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: read
    strategy:
      matrix:
        arch:
          - x86_64-unknown-linux-musl
          - i686-unknown-linux-musl
          - mips-unknown-linux-musl
          - mips-unknown-linux-gnu
          - aarch64-unknown-linux-gnu
          - aarch64-unknown-linux-musl
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: cargo install cross --git https://github.com/cross-rs/cross
      - run: cross build --release --target ${{ matrix.arch }}  --package east_agent
      - uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.arch }}
          path: target/${{ matrix.arch }}/release/east*
      
      - run: zip -j agent_${{ matrix.arch }} target/${{ matrix.arch }}/release/east*
    
      - name: Release Drafter
        id: create_release
        uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}   

      - name: Upload Release Asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} 
          asset_path: agent_${{ matrix.arch }}.zip
          asset_name: agent_${{ matrix.arch }}.zip
          asset_content_type: application/zip
